import Head from "next/head";
import Message from "../components/Message";
import { db } from "../utils/firebase";
import react from "react";
import { FaComments } from "react-icons/fa";
import { FcLikePlaceholder, FcLike } from "react-icons/fc";
import {
  collection,
  doc,
  orderBy,
  query,
  onSnapshot,
} from "firebase/firestore";
import Link from "next/link";
export default function Home() {
  const [allPosts, setallPosts] = react.useState([]);
  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timeStamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setallPosts(
        snapshot.docs.map((doc) => ({
          ...doc.data(),
          id: doc.id,
        }))
      );
    });
    return unsubscribe;
  };
  react.useEffect(() => {
    getPosts();
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2>What's happening...</h2>
        {allPosts.map((post) => (
          <Message key={post.id} {...post}>
            <div style={{display:"flex"}}>
            <Link
              href={{ pathname: `${post.id}`, query: { ...post } }}
              style={{ display: "flex" }}
            >
              <FaComments size={20} color="white"></FaComments>
            </Link>
            </div>
            <div>
              <FcLike size={20}></FcLike>
            </div>
          </Message>
        ))}
      </div>
    </div>
  );
}
